EleutherAI/oslo

oslo/torch/nn/__init__.py
oslo/torch/nn/parallel/data_parallel/fsdp/__init__.py
oslo/torch/nn/parallel/data_parallel/fsdp/_optim_utils.py
oslo/torch/nn/parallel/data_parallel/fsdp/_shard/_utils.py
oslo/torch/nn/parallel/data_parallel/fsdp/_shard/checkpoint/metadata.py
oslo/torch/nn/parallel/data_parallel/fsdp/_shard/checkpoint/resharding.py
oslo/torch/nn/parallel/data_parallel/fsdp/_shard/checkpoint/state_dict_saver.py
oslo/torch/nn/parallel/data_parallel/fsdp/_shard/op_registry_utils.py
oslo/torch/nn/parallel/data_parallel/fsdp/_shard/sharded_tensor/_ops/chunk.py
oslo/torch/nn/parallel/data_parallel/fsdp/_shard/sharded_tensor/api.py
oslo/torch/nn/parallel/data_parallel/fsdp/_shard/sharded_tensor/metadata.py
oslo/torch/nn/parallel/data_parallel/fsdp/_shard/sharder.py
oslo/torch/nn/parallel/data_parallel/fsdp/_shard/sharding_spec/__init__.py
oslo/torch/nn/parallel/data_parallel/fsdp/_shard/sharding_spec/api.py
oslo/torch/nn/parallel/data_parallel/fsdp/fully_sharded_data_parallel.py
oslo/torch/nn/parallel/data_parallel/fsdp/shard_utils.py
oslo/torch/nn/parallel/data_parallel/fsdp/sharded_grad_scaler.py
oslo/torch/nn/parallel/expert_parallel/_ops.py
oslo/torch/nn/parallel/sequence_parallel/sequence_data_parallel.py
oslo/torch/nn/parallel/tensor_parallel/tensor_parallel.py
oslo/transformers/mapping_utils.py
oslo/transformers/tasks/data_albert_pretraining.py
oslo/transformers/tasks/data_bart_pretraining.py
oslo/transformers/tasks/data_base.py
oslo/transformers/tasks/data_bert_pretraining.py
oslo/transformers/tasks/data_t5_pretraining.py

- Add FSDP mapping
- Add FSDP mapping for `transformer_auto_wrap_policy`
- resolved #29

[#29] Add FSDP mapping

---

oslo/transformers/mapping_utils.py

- Add GPTNeoX transformers mapping

add GPT-NeoX mapping

---

oslo/torch/nn/parallel/pipeline_parallel/pipeline_parallel.py
tests/torch/nn/parallel/pipeline_parallel/test_pp.py

- Modify PP to functional
- Modify PP to functional
- resolved #50

[#50] Modify PP to functional

---

oslo/torch/nn/parallel/sequence_parallel/sequence_data_parallel.py
oslo/torch/utils/data/data_collators.py
oslo/transformers/tasks/data_albert_pretraining.py
oslo/transformers/tasks/data_bart_pretraining.py
oslo/transformers/tasks/data_base.py
oslo/transformers/tasks/data_bert_pretraining.py
oslo/transformers/tasks/data_causal_lm.py
oslo/transformers/tasks/data_masked_lm.py
oslo/transformers/tasks/data_sequence_classification.py
oslo/transformers/tasks/data_summarization.py
oslo/transformers/tasks/data_t5_pretraining.py
oslo/transformers/tasks/data_token_classification.py

- Make sequence parallel splitting automatic
- Make sequence parallel splitting automatic
- resolved #55

[#55] Make sequence parallel splitting automatic

---

oslo/torch/distributed/_initializers/initializer.py
oslo/torch/distributed/_initializers/initializer_expert.py
oslo/torch/distributed/parallel_context.py
oslo/torch/distributed/parallel_mode.py
oslo/torch/nn/parallel/expert_parallel/_ops.py
oslo/torch/nn/parallel/expert_parallel/expert_parallel.py
oslo/torch/nn/parallel/expert_parallel/experts.py
oslo/torch/nn/parallel/expert_parallel/layers.py
oslo/torch/nn/parallel/expert_parallel/mapping.py
oslo/transformers/mapping_utils.py
tests/torch/nn/parallel/expert_parallel/wrapper_test/init_test/gpt2_pr_ep.py
tests/torch/nn/parallel/expert_parallel/wrapper_test/init_test/gpt2_pr_moe.py
tests/torch/nn/parallel/expert_parallel/wrapper_test/init_test/utils.py

- switch code base of expert parallel from colossalai to deepspeed
- switch code base to deepspeed 
- implement and test expert parallel + data parallel 
- resolved #44

[#44] switch: code base of expert parallel from colossalai to deepspeed

---

README.md
requirements.txt
setup.py

- Formatting & Version Compability Commitment in setup.py
- This small pull request changes setup.py in the direction of ensuring and redirecting OSLO users to make their build with the correct PyTorch version which >= 1.11.0 and also add warnings for invalid Python versions. Forces users to initialize their build of OSLO with pre-installed torch >= 1.11.0.

(chore) add small formattings & versioning to setup.py, add README.md

---

oslo/torch/nn/parallel/sequence_parallel/sequence_data_parallel.py
oslo/torch/utils/data/__init__.py
oslo/torch/utils/data/data_collators.py
tests/torch/utils/data/test_data_collators.py

- Rename SP
- Rename SequenceDataParallel to SequenceParallel
- resolved #67

[#67] Rename SP

---

oslo/torch/nn/parallel/data_parallel/_fsdp/fully_sharded_data_parallel.py

- Refactoring transformers wrap
- resolved #77

[#77] refactoring transformers wrap

---

oslo/torch/nn/parallel/tensor_parallel/_1d/_wrapper.py
oslo/torch/nn/parallel/tensor_parallel/_2d/_wrapper.py
oslo/torch/nn/parallel/tensor_parallel/_2p5d/_wrapper.py
oslo/torch/nn/parallel/tensor_parallel/_3d/_wrapper.py
oslo/torch/nn/parallel/tensor_parallel/tensor_parallel.py

There is a bug after changing _TensorParallelMappingForHuggingFace to _ParallelMapping in oslo/oslo/transformers/mapping_utils.py
Changed _wrapper.py in tensor_parallel to sync with the previous submission. (No _TensorParallelMappingForHuggingFace found error)
- resolved #88

fix  _TensorParallelMappingForHuggingFace error

---

oslo/torch/utils/extensions.py
tests/torch/nn/parallel/tensor_parallel/1d/deparallel/test_deparallelize.py

[hotfix] fixed tp deparallelized deadlock

---

oslo/torch/nn/parallel/expert_parallel/expert_parallel.py
oslo/torch/nn/parallel/expert_parallel/experts.py
tests/torch/nn/parallel/expert_parallel/wrapper_test/init_test/gpt2_deparallelize.py

- Deparallelize expert parallel
- Implement features of deparallelization for expert parallel 
- resolved #82

[#82] implement deparallelization feature for expert_parallel

---

oslo/transformers/__init__.py

- Add oslo models to transformers
-
- resolved #107

Add oslo models to transformers

---

oslo/transformers/trainer.py
oslo/transformers/training_args.py

- Update trainer to modify code by additional requirements 
- Add compute_pp_loss function using on training_step 
- Modify world size, rank on trainer
- resolved #00

Update trainer to modify code by additional requirements 

---

oslo/transformers/oslo_init.py

Remove Config class and Modify OsloConfig
-
- resolved #00

Trainer new

---

oslo/torch/nn/modules/embedding.py
oslo/torch/nn/modules/layer_norm.py
oslo/torch/nn/modules/linear.py
oslo/torch/nn/parallel/tensor_parallel/_1d/_ops.py
oslo/torch/nn/parallel/tensor_parallel/_1d/_wrapper.py
oslo/torch/nn/parallel/tensor_parallel/__init__.py
oslo/torch/nn/parallel/tensor_parallel/mapping.py
oslo/torch/nn/parallel/tensor_parallel/tensor_parallel.py
oslo/torch/utils/extensions.py
oslo/transformers/constants.py
oslo/transformers/mapping_utils.py
oslo/transformers/oslo_init.py

- Fix T5 TP bugs by disabling gather on Embedding1D.
- Fix T5 bugs by disabling gather on Embedding1D.
- Remove memory priority (sequence-parallel at Megatron-LM)
- resolved #117

[fix] T5 fix TP bugs

---

.pre-commit-config.yaml
oslo/torch/_C/csrc/includes/tqdm.h
oslo/torch/nn/parallel/expert_parallel/expert_parallel.py

- Replace gitlab repository in pre-commit with github
- resolved #120

replace gitlab repo with github

---

oslo/torch/nn/parallel/tensor_parallel/_2d/_wrapper.py
oslo/torch/nn/parallel/tensor_parallel/_2p5d/_wrapper.py
oslo/torch/nn/parallel/tensor_parallel/_3d/_wrapper.py
tests_deprecated/torch/nn/parallel/tensor_parallel/2p5d/test_wrapper_2p5d.py

remove class_replace argument from wrappers

---

oslo/torch/distributed/_initializers/initializer_expert.py
oslo/torch/nn/parallel/expert_parallel/_ops.py
oslo/torch/nn/parallel/expert_parallel/expert_parallel.py
oslo/torch/nn/parallel/expert_parallel/experts.py
oslo/torch/nn/parallel/expert_parallel/layers.py
oslo/torch/nn/parallel/expert_parallel/mapping.py
oslo/torch/nn/parallel/expert_parallel/utils.py
oslo/torch/utils/extensions.py
oslo/transformers/mapping_utils.py
tests_deprecated/torch/nn/parallel/expert_parallel/gpt2/gpt2.py
tests_deprecated/torch/nn/parallel/expert_parallel/gpt2/gpt2_deparallelize.py
tests_deprecated/torch/nn/parallel/expert_parallel/gpt2/gpt2_load.py
tests_deprecated/torch/nn/parallel/expert_parallel/gpt2/gpt2_pr_ep.py
tests_deprecated/torch/nn/parallel/expert_parallel/gpt2/gpt2_pr_moe.py
tests_deprecated/torch/nn/parallel/expert_parallel/gpt2/gpt2_save.py
tests_deprecated/torch/nn/parallel/expert_parallel/gpt2/utils.py

- Save Deparallelized Expert Parallel Model
- Implement features for save/load for deparallelized expert parallel model 
- resolved #101

[#101] impleent save/load feature for expert_parallel

---

oslo/torch/nn/parallel/data_parallel/data_parallel.py

Related to #137
For now, our implementation of DDP does not support long tensor input, so I fixed it.

[Fix] Support long tensor for DDP backward

---

requirements.txt

```
Traceback (most recent call last):
File "test_oslo.py", line 9, in <module>
import oslo
File "/home/oslo/oslo/__init__.py", line 2, in <module>
from oslo.torch.utils.extensions import ready_torch
File "/home/oslo/oslo/torch/utils/extensions.py", line 12, in <module>
from oslo.torch.nn.parallel.pipeline_parallel.pipeline_parallel import (
File "/home/oslo/oslo/torch/nn/parallel/__init__.py", line 1, in <module>
from oslo.torch.nn.parallel.pipeline_parallel import *
File "/home/oslo/oslo/torch/nn/parallel/pipeline_parallel/__init__.py", line 1, in <module>
from oslo.torch.nn.parallel.pipeline_parallel.pipeline_parallel import (
File "/home/oslo/oslo/torch/nn/parallel/pipeline_parallel/pipeline_parallel.py", line 8, in <module>
from transformers.utils import ModelOutput …
```

[Deps] Add transformers package

---

oslo/torch/nn/parallel/data_parallel/__init__.py

Add set_params_to_ignore in init file.
This function is for ignoring params for ddp
- resolved #00

[Fix] add set_params_to_ignore in init file

---

oslo/torch/nn/parallel/data_parallel/__init__.py

- specify import of zero optimizer
- It's a very trivial thing, but I've specified the import of the zero optimizer.

[Fix] specify import of zero optimizer

---

oslo/torch/nn/parallel/data_parallel/data_parallel.py

When the output of a DDP model is `dict`, there is an issue where the DDP model doesn't work correctly.
I fixed it.

[Fix] Handle case with mapping or sequence output

---

tests_deprecated/torch/nn/parallel/data_parallel/zero/test_hybrid.py

- [Fix] zero optimizer w/ tensor parallel test
- ZeRO was not running in tensor parallel mode, so I fixed this by switching to a model from `transformers`.
- N/A

[Fix] zero optimizer w/ tensor parallel test

---

oslo/torch/nn/modules/embedding.py
oslo/torch/nn/parallel/tensor_parallel/_2d/_wrapper.py
oslo/transformers/mapping_utils.py

Revert ViT TP2D logic

---

oslo/torch/nn/parallel/data_parallel/zero/sharded_optim/__init__.py
oslo/torch/nn/parallel/data_parallel/zero/sharded_optim/heterogeneous_optim.py

- [Enhance] add zero3 opt
- A wrapper for optimizer. ``_FullyShardedDataParallel`` and ``HeterogeneousZeroOptimizer`` implement Zero Redundancy Optimizer (ZeRO state-3)
- N/A

[Enhance] add zero3 opt

---

oslo/transformers/tasks/data_bart_pretraining.py
oslo/transformers/tasks/data_base.py
tests_deprecated/transformers/tasks/test_data_bart_pretraining.py
tests_deprecated/transformers/tasks/test_data_base.py

BART TASK SOURCE UPDATE 
BART DENOSING SOURCE Modifying, 
BART Task Test source

[MOD] BART TASK Update

---

oslo/torch/utils/extensions.py

- Change save_pretrained and from_parallelized functional annotation
- (save_pretrained function) bug load_state_dict and change the code order 
- (from_parallelized function) Add functional annotation
- resolved #00

Change save_pretrained and from_parallelized annotation

---

oslo/torch/utils/__init__.py
oslo/torch/utils/logging/__init__.py
oslo/torch/utils/logging/logger.py
tests_deprecated/torch/utils/logging.py

- [Add] Distributed Logger Utility for PyTorch
- This PR introduces a distributed event logger class that is essentially based on Python's built-in `logging` module. The DistributedLogger class provides an easy-to-use API for logging events in a distributed environment using PyTorch.
- N/A

[Add] Distributed Logger Utility for PyTorch

---

oslo/torch/nn/parallel/data_parallel/_utils.py
oslo/torch/nn/parallel/data_parallel/zero/fully_sharded_data_parallel.py

- [Del] grad handle free storage func
- This PR addresses the issue related to the `free_storage` function. We've found that this function was causing numerous bugs, resulting in inconsistent behavior of our memory management system.
- N/A

[Del] grad handle free storage func

---

tests_deprecated/torch/nn/parallel/data_parallel/zero/heterogeneous_manager/test_chunk.py
tests_deprecated/torch/nn/parallel/data_parallel/zero/heterogeneous_manager/test_chunk_manager.py
tests_deprecated/torch/nn/parallel/data_parallel/zero/sharded_optim/test_hetero_step.py
tests_deprecated/torch/nn/parallel/data_parallel/zero/test_fsdp_wrapper.py
tests_deprecated/torch/nn/parallel/data_parallel/zero/test_grad.py
tests_deprecated/torch/nn/parallel/data_parallel/zero/test_state_dict.py

- [Add] ZeRO3 unit test
- A simple test code for zero redundancy optimizer strategy 3 has been introduced.
- N/A

[Add] ZeRO3 unit test

---

oslo/torch/nn/parallel/data_parallel/zero/fully_sharded_data_parallel.py
oslo/torch/nn/parallel/data_parallel/zero/sharded_optim/heterogeneous_optim.py
oslo/torch/utils/logging/logger.py

- [Fix] Change the logger of ZeRO3
- Change the logger of FSDP to consider distributed state
- N/A

[Fix] Change the logger of ZeRO3

---

oslo/torch/nn/parallel/data_parallel/zero/chunk/chunk.py
oslo/torch/nn/parallel/data_parallel/zero/chunk/manager.py
oslo/torch/nn/parallel/data_parallel/zero/chunk/utils.py
oslo/torch/nn/parallel/data_parallel/zero/fully_sharded_data_parallel.py
oslo/torch/nn/parallel/data_parallel/zero/heterogeneous_hook.py
oslo/torch/nn/parallel/data_parallel/zero/heterogeneous_manager.py
oslo/torch/nn/parallel/data_parallel/zero/memory_tracer/chunk_memstats_collector.py
oslo/torch/nn/parallel/data_parallel/zero/memory_tracer/memory_monitor.py
oslo/torch/nn/parallel/data_parallel/zero/memory_tracer/memory_stats.py
oslo/torch/nn/parallel/data_parallel/zero/memory_tracer/param_runtime_order.py
oslo/torch/nn/parallel/data_parallel/zero/memory_tracer/utils.py
oslo/torch/nn/parallel/data_parallel/zero/placement_policy.py
oslo/torch/nn/parallel/data_parallel/zero/sharded_optim/heterogeneous_optim.py

- [Add] copyright for ZeRO3
- N/A
- N/A

[Add] copyright for ZeRO3

---

oslo/torch/nn/parallel/data_parallel/__init__.py
oslo/torch/nn/parallel/data_parallel/data_parallel.py
oslo/torch/nn/parallel/data_parallel/zero/fully_sharded_data_parallel.py
oslo/torch/nn/parallel/data_parallel/zero/sharded_optim/heterogeneous_optim.py

- [Feature] Enhance Distributed Data Parallel wrapper with ZeRO
This PR introduces a significant enhancement to the Distributed Data Parallel (DDP) wrapper in the OSLO library. It adds the capability to utilize different sharding strategies during distributed training, allowing better control over memory footprint across multiple GPUs or machines.
Here are the key changes:
1. **Sharding Strategy Enum**: A new enum `ShardingStrategy` is introduced, which includes `SHARD_OP`, `SHARD_GRAD_OP`, and `FULL_SHARD` options. These determine how model parameters and optimizer states are partitioned across GPUs. 
2. **DistributedDataParallel Changes**: The signature of the `DistributedDataParallel` function is updated to incorporate these new sharding strategies, along with additional configuration …

[Feature] Enhance Distributed Data Parallel wrapper with ZeRO

---

oslo/torch/distributed/parallel_context.py
tests_deprecated/torch/nn/parallel/pipeline_parallel/test_pp4.py

Fix rpc bug on AWS
- rpc.TensorPipeRpcBackendOptions returns an error when run on AWS.
related issues
- https://github.com/pytorch/pytorch/issues/65022
- https://github.com/pytorch/tensorpipe/issues/413
- https://github.com/pytorch/pytorch/issues/65093
- https://github.com/pytorch/pytorch/issues/65022
- resolved #00

[Fix] rpc not working on aws

---

oslo/torch/nn/parallel/pipeline_parallel/pipeline_parallel.py

Give num_concurrent as argument
- Simple change in pipeline parallel. Give num_concurrent as argument.

 Give num_concurrent as argument
